FreeCodeCamp.MongoDBAndEFCore/Controllers/ReservationController.cs
using FreeCodeCamp.MongoDBAndEFCore.Models;
using FreeCodeCamp.MongoDBAndEFCore.Services;
using FreeCodeCamp.MongoDBAndEFCore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace FreeCodeCamp.MongoDBAndEFCore.Controllers;

public class ReservationController : Controller
{
    private readonly IReservationService _ReservationService;
    private readonly IRestaurantService _RestaurantService;

    public ReservationController(IReservationService ReservationService, IRestaurantService RestaurantService)
    {
        _ReservationService = ReservationService;
        _RestaurantService = RestaurantService;
    }

    public IActionResult Index()
    {
        ReservationListViewModel viewModel = new ReservationListViewModel()
        {
            Reservations = _ReservationService.GetAllReservations()
        };
        return View(viewModel);
    }

    public IActionResult Add(ObjectId restaurantId)
    {
        var selectedRestaurant = _RestaurantService.GetRestaurantById(restaurantId);

        ReservationAddViewModel reservationAddViewModel = new ReservationAddViewModel();

        reservationAddViewModel.Reservation = new Reservation();
        reservationAddViewModel.Reservation.RestaurantId = selectedRestaurant.Id;
        reservationAddViewModel.Reservation.RestaurantName = selectedRestaurant.Name;
        reservationAddViewModel.Reservation.Date = DateTime.UtcNow;

        return View(reservationAddViewModel);
    }

    [HttpPost]
    public IActionResult Add(ReservationAddViewModel reservationAddViewModel)
    {
        Reservation newReservation = new()
        {
            RestaurantId = reservationAddViewModel.Reservation.RestaurantId,
            Date = reservationAddViewModel.Reservation.Date,
        };

        _ReservationService.AddReservation(newReservation);
        return RedirectToAction("Index");
    }

    public IActionResult Edit(string Id)
    {
        if (Id == null || string.IsNullOrEmpty(Id))
        {
            return NotFound();
        }

        var selectedReservation = _ReservationService.GetReservationById(new ObjectId(Id));
        return View(selectedReservation);
    }

    [HttpPost]
    public IActionResult Edit(Reservation reservation)
    {
        try
        {
            var existingReservation = _ReservationService.GetReservationById(reservation.Id);
            if (existingReservation != null)
            {
                _ReservationService.EditReservation(reservation);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", $"Reservation with ID {reservation.Id} does not exist!");
            }
        }
        catch (Exception ex)
        {
            ModelState.AddModelError("", $"Updating the reservation failed, please try again! Error: {ex.Message}");
        }

        return View(reservation);
    }

    public IActionResult Delete(string Id)
    {
        if (Id == null || string.IsNullOrEmpty(Id))
        {
            return NotFound();
        }

        var selectedReservation = _ReservationService.GetReservationById(new ObjectId(Id));
        return View(selectedReservation);
    }

    [HttpPost]
    public IActionResult Delete(Reservation reservation)
    {
        if (reservation.Id == null)
        {
            ViewData["ErrorMessage"] = "Deleting the reservation failed, invalid ID!";
            return View();
        }

        try
        {
            _ReservationService.DeleteReservation(reservation);
            TempData["ReservationDeleted"] = "Reservation deleted successfully";

            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            ViewData["ErrorMessage"] = $"Deleting the reservation failed, please try again! Error: {ex.Message}";
        }

        var selectedRestaurant = _ReservationService.GetReservationById(reservation.Id);
        return View(selectedRestaurant);
    }
}

FreeCodeCamp.MongoDBAndEFCore/Controllers/RestaurantController.cs
using FreeCodeCamp.MongoDBAndEFCore.Models;
using FreeCodeCamp.MongoDBAndEFCore.Services;
using FreeCodeCamp.MongoDBAndEFCore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace FreeCodeCamp.MongoDBAndEFCore.Controllers;

public class RestaurantController : Controller
{
    private readonly IRestaurantService _RestaurantService;

    public RestaurantController(IRestaurantService RestaurantService)
    {
        _RestaurantService = RestaurantService;
    }
    public IActionResult Index()
    {
        RestaurantListViewModel viewModel = new()
        {
            Restaurants = _RestaurantService.GetAllRestaurants(),
        };
        return View(viewModel);
    }

    public IActionResult Add()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Add(RestaurantAddViewModel restaurantAddViewModel)
    {
        if (ModelState.IsValid)
        {
            Restaurant newRestaurant = new()
            {
                Name = restaurantAddViewModel.Restaurant.Name,
                Borough = restaurantAddViewModel.Restaurant.Borough,
                Cuisine = restaurantAddViewModel.Restaurant.Cuisine
            };

            _RestaurantService.AddRestaurant(newRestaurant);
            return RedirectToAction("Index");
        }

        return View(restaurantAddViewModel);
    }

    public IActionResult Edit(ObjectId id)
    {
        if (id == null || id == ObjectId.Empty)
        {
            return NotFound();
        }

        var selectedRestaurant = _RestaurantService.GetRestaurantById(id);
        return View(selectedRestaurant);
    }

    [HttpPost]
    public IActionResult Edit(Restaurant restaurant)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _RestaurantService.EditRestaurant(restaurant);
                return RedirectToAction("Index");
            }
            else
            {
                return BadRequest();
            }
        }
        catch (Exception ex)
        {
            ModelState.AddModelError("", $"Updating the restaurant failed, please try again! Error: {ex.Message}");
        }

        return View(restaurant);
    }

    public IActionResult Delete(ObjectId id)
    {
        if (id == null || id == ObjectId.Empty)
        {
            return NotFound();
        }

        var selectedRestaurant = _RestaurantService.GetRestaurantById(id);
        return View(selectedRestaurant);
    }

    [HttpPost]
    public IActionResult Delete(Restaurant restaurant)
    {
        if (restaurant.Id == ObjectId.Empty)
        {
            ViewData["ErrorMessage"] = "Deleting the restaurant failed, invalid ID!";
            return View();
        }

        try
        {
            _RestaurantService.DeleteRestaurant(restaurant);
            TempData["RestaurantDeleted"] = "Restaurant deleted successfully!";

            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            ViewData["ErrorMessage"] = $"Deleting the restaurant failed, please try again! Error: {ex.Message}";
        }

        var selectedRestaurant = _RestaurantService.GetRestaurantById(restaurant.Id);
        return View(selectedRestaurant);
    }
}

FreeCodeCamp.MongoDBAndEFCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FreeCodeCamp.MongoDBAndEFCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FreeCodeCamp.MongoDBAndEFCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FreeCodeCamp.MongoDBAndEFCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @* <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> *@
                @*     <ul class="navbar-nav flex-grow-1"> *@
                @*         <li class="nav-item"> *@
                @*             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
                @*         </li> *@
                @*         <li class="nav-item"> *@
                @*             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
                @*         </li> *@
                @*     </ul> *@
                @* </div> *@
                <div class="collapse navbar-collapse justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservations</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FreeCodeCamp.MongoDBAndEFCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>